version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  tweet:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run tweet
workflows:
  tweet-workflow:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tweet